refine and improvement
pado-labs/pado-ao-sdk pull request #14
Opened 2024-05-13 02:12 UTC by ujnss

- add dataId for task submit.
- add transfer, transferAOCREDToTask helper functions. 
- add AOCRED_PROCESS_ID to config.js.

2024-05-13 07:04 UTC, ujnss commented
Add the usage of `upload data` for data provider, `keygen`, `submit task` for data user.

2024-05-13 09:04 UTC, ujnss commented
using getMessageResultData for handing exception and getting result

2024-05-14 02:42 UTC, fksyuan requested changes

2024-05-14 02:42 UTC, fksyuan commented on src/config.js
NODE_INDICES and NODE_NAMES are best to take it from ao process

2024-05-14 02:42 UTC, fksyuan commented on src/keygen.ts
> +export const generateKey = async (): Promise<string> => {
This method don't need async.

2024-05-14 02:42 UTC, fksyuan commented on src/keygen.ts
Don't need this file, can export directly from index.ts

2024-05-14 02:42 UTC, fksyuan commented on src/submittask.ts
The relationship with index.ts must be considered

2024-05-14 02:42 UTC, fksyuan commented on src/transferaocredtotask.ts
The relationship with index.ts must be considered

2024-05-14 02:42 UTC, fksyuan commented on src/uploaddata.ts
The relationship with index.ts must be considered

2024-05-14 03:13 UTC, ujnss commented
`keygen`, `uploaddata`, `transferaocredtotask`, `submittask` are just examples of usage, the exported functions will be moved to index.

2024-05-16 02:39 UTC, fksyuan approved these changes

2024-05-16 02:39 UTC, merged